### ISSUE TITLE
Change the red background for documention

### ISSUE THREAD

**Issue by bykka** [richard-scryber/scryber.core#105]
[Website with official documentation](https://scrybercore.readthedocs.io/en/latest/index.html) has the red background what makes it hard to read. 

Please delete it or change the colour on something on something more friendly for eyes.

File for fixing - docs/_static/css/scrybertheme.css

<img width="1674" alt="image" src="https://github.com/richard-scryber/scryber.core/assets/489997/d80f28b1-55b3-41ef-ac49-5b634d5fafe3">

For example colour #ebd8d8 looks much better for eyes
<img width="1671" alt="image" src="https://github.com/richard-scryber/scryber.core/assets/489997/93f684c0-c8e8-49ac-8629-f3eee6796534">

**Comment by richard-scryber** [comment]
Wow - thank you for raising this Pavlo! Not sure how it got like that, but definitely agree the red is a little bit disastrous!

**Comment by richard-scryber** [comment]
This should now be sorted. I believe ReadTheDocs have updated their default theme, and this then brought in a test I was trying to run. Anyway - sorted. Could probably do with some style updates (along with the content). Let me know if it is not working for you. Otherwise I will close in a day or two.

**Comment by bykka** [comment]
Thank you. Now it looks better.
And you're right Alabaster is a new default theme https://alabaster.readthedocs.io/en/latest/
Not my favorite one because the left-side menu is too close to the content and has the same font color and size that something it takes time to distinguish where is what. BTW sections of the menu are not easy to notice as well.
<img width="1111" alt="image" src="https://github.com/richard-scryber/scryber.core/assets/489997/057cd4f2-1ef4-4f03-9d49-75e2e29b9fc3">

For the version 5.0.6 there is theme [Read the Docs](https://sphinx-themes.org/#theme-sphinx-rtd-theme)

**Comment by richard-scryber** [comment]
I will take a look at now the available themes. The 'Read the Docs' one is good, but might be a more usable one. Thank you for the links 👍
