### ISSUE TITLE
Security property support

### ISSUE THREAD

**Issue by RS-code-r** [richard-scryber/scryber.core#23]
Is it possible to set some security options for the generated pdf, like: printing, document composition, signature?
Will this feature be added in the future? (Unfortunately, there is no entry for this in the documentation)

What about PDF Signatures? Will this also be added later?

**Comment by richard-scryber** [comment]
Hey, thanks for the reach out.
 We do have some code in old dot net still to port for extensions to the core library, including document security (plus modifications, charts and attachments). 

Nothing on signing, at the moment, but looking at the available api's to do this. However I have added it to the backlog. 
[https://github.com/users/richard-scryber/projects/1](https://github.com/users/richard-scryber/projects/1)

**Comment by richard-scryber** [comment]
Added security support in 5.0.5

And added documentation here
https://scrybercore.readthedocs.io/en/latest/document_security.html
