### ISSUE TITLE
Image data for 2 or more images in one document are the same

### ISSUE THREAD

**Issue by ggrgovski** [richard-scryber/scryber.core#24]
Hi Richard,

I found one issue when I have 2 images in one document for example:
`<doc:Image img-data="imageData1"/>
<doc:Image img-data="imageData2"/>`

For some reason on the second image the data is the same as on the first image.
Is that something that you are aware of or needs to be investigated ?

Thanks.

**Comment by richard-scryber** [comment]
Thanks Gjorgji.
Just so I am clear - these are being dynamically assigned from parameters, or model data in your template?

They certainly should not get mixed up, so I can take a look and see what is going on.

**Comment by ggrgovski** [comment]
Hey Richard,

I'm binding both images from Model data.

**Comment by richard-scryber** [comment]
Going to close this Gjorgii, I think this is working in the latest release. Thanks for your input :-)
