### ISSUE TITLE
CSS border botton, top, left and right

### ISSUE THREAD

**Issue by aMedh** [richard-scryber/scryber.core#33]
CSS border botton, top, left and tight does not seem to work.

border-bottom
border-top
border-left
border-right

.example-border {
    border-left: 1px solid #eee;
}

Feels like more CSS elements not working properly. Is there a list with confirmed working elements?

**Comment by richard-scryber** [comment]
Hey, yeah. There are definitely some properties we don't currently support... including relative positions. 
We are going through the documentation phase now, so hopefully we can give a complete list, but this may help with known style keys.

    public static class CSSStyleItems
    {
        public const string Border = "border";
        public const string BorderWidth = "border-width";
        public const string BorderStyle = "border-style";
        public const string BorderColor = "border-color";

        public const string FillColor = "color";

        public const string Background = "background";
        public const string BackgroundImage = "background-image";
        public const string BackgroundColor = "background-color";
        public const string BackgroundRepeat = "background-repeat";
        public const string BackgroundSize = "background-size";
        public const string BackgroundPosition = "background-position";

        public const string FontStyle = "font-style";
        public const string FontWeight = "font-weight";
        public const string FontSize = "font-size";
        public const string FontFamily = "font-family";
        public const string FontLineHeight = "line-height";
        public const string Font = "font";
        public const string FontSource = "src";

        public const string Margins = "margin";
        public const string MarginsLeft = "margin-left";
        public const string MarginsRight = "margin-right";
        public const string MarginsTop = "margin-top";
        public const string MarginsBottom = "margin-bottom";

        public const string Padding = "padding";
        public const string PaddingLeft = "padding-left";
        public const string PaddingRight = "padding-right";
        public const string PaddingTop = "padding-top";
        public const string PaddingBottom = "padding-bottom";

        public const string Opacity = "opacity";
        public const string FillOpacity = "fill-opacity";

        public const string ColumnCount = "column-count";
        public const string ColumnGap = "column-gap";

        public const string ColumnSpan = "column-span";

        public const string Left = "left";
        public const string Top = "top";

        public const string Width = "width";
        public const string Height = "height";
        public const string MinimumWidth = "min-width";
        public const string MinimumHeight = "min-height";
        public const string MaximumWidth = "max-width";
        public const string MaximumHeight = "max-height";

        public const string TextAlign = "text-align";
        public const string VerticalAlign = "vertical-align";

        public const string Display = "display";
        public const string Overflow = "overflow";

        public const string TextDecoration = "text-decoration";
        public const string LetterSpacing = "letter-spacing";
        public const string WordSpacing = "word-spacing";

        public const string WhiteSpace = "white-space";

        public const string ListStyleType = "list-style-type";
        public const string ListStyle = "list-style";

        public const string PageBreakInside = "page-break-inside";
        public const string PageBreakAfter = "page-break-after";
        public const string PageBreakBefore = "page-break-before";
        public const string PageSize = "size";
        public const string PageGroupName = "page";

        public const string PositionModeType = "position";

        public const string StrokeColor = "stroke";
        public const string StrokeOpacity = "stroke-opacity";
        public const string StrokeWidth = "stroke-width";
        public const string StrokeDash = "stroke-dasharray";
     }

**Comment by aMedh** [comment]
Thanks for fast reply. Great I will save that list.

Love the framework. Supereasy to get started with. Looks promising for the future. Keep up the good work.

**Comment by richard-scryber** [comment]
This should be working in the latest version now
