### ISSUE TITLE
Typo in documentation example

### ISSUE THREAD

**Issue by FlorianTrabold** [richard-scryber/scryber.core#39]
https://github.com/richard-scryber/scryber.core/blob/master/docs/document_pagenumbering.rst

`<footer>`
`    <p class='print-only foot'> Page <page /> of <page propery='total' /></p>`
`</footer>`

(Typo at "propery" - as is displays "Page 1 of 1" and "Page 2 of 2" in a two-page-document)

should be

`<footer>`
`    <p class='print-only foot'> Page <page /> of <page property='total' /></p>`
`</footer>`

**Comment by richard-scryber** [comment]
That is awesome - thanks for picking this up Florian. Will update now :-)

**Comment by richard-scryber** [comment]
Updated. Appreciate the feedback
