### ISSUE TITLE
Output totaly different then HTML template

### ISSUE THREAD

**Issue by jeroenvipper** [richard-scryber/scryber.core#50]
The plain HTML template does respect the html and css, while the actual output after rendering to PDF look totally different.

Replicate:
Create .net code web API application 

Use this code:
           var path = System.Environment.CurrentDirectory;
            path = System.IO.Path.Combine(path, "Templates/ticket.html");

            using var doc = Document.ParseDocument(path);
            //And save it to a file or a stream
            using var stream = new System.IO.FileStream("ticket.pdf", System.IO.FileMode.Create);
            doc.SaveAsPDF(stream);

This HTML template:
<!DOCTYPE HTML>
<html lang='en' xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <title>Hello World</title>

    
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Fraunces:ital,wght@0,400;0,700;1,400;1,700&amp;display=swap"
          title="Fraunces" />

    <style>
        body {
            font-family: 'Fraunces', sans-serif;
            font-size: 14pt;
        }

        .fullroute-header {
            width: 700px;
            height: 87px;
            background: #692E87 0% 0% no-repeat padding-box;
            box-shadow: 0px 3px 6px #00000029;
            border-radius: 10px 10px 0px 0px;
            opacity: 1;
            overflow: hidden;
        }

        .fullroute-header-text {
            padding-top: 72px;
            height: 100%;
            width: 300px;
            text-align: right;
            letter-spacing: 0px;
            color: #FFFFFF;
            text-transform: uppercase;
            opacity: 1;
            float: right;
            overflow: hidden;
        }

        .fullroute-overview {
            top: 40px;
            left: 57px;
            width: 700px;
            height: 587px;
            background: #692E87 0% 0% no-repeat padding-box;
            box-shadow: 0px 3px 6px #00000029;
            border-radius: 0px 0px 10px 10px;
            opacity: 1;
            overflow: hidden;
        }

        .fullroute-overview-bookingref {
            top: 10px;
            height: 50px;
            width: 700px;
            color: #FFFFFF;
            text-transform: uppercase;
            opacity: 1;
            float: left;
            background-color: yellow;
            overflow: hidden;
        }

        .fullroute-overview-depart {
            top: 20px;
            height: 100%;
            width: 300px;
            color: #FFFFFF;
            text-transform: uppercase;
            opacity: 1;
            float: left;
            background-color: red;
            overflow: hidden;
        }

        .fullroute-overview-return {
            top: 20px;
            height: 100%;
            width: 300px;
            text-align: right;
            color: #FFFFFF;
            text-transform: uppercase;
            opacity: 1;
            float: right;
            background-color: green;
            overflow: hidden;
        }
    </style>
    
    <base href='https://raw.githubusercontent.com/richard-scryber/scryber.core/master/Scryber.Core.UnitTest/Content/' />
</head>
<body>
    <div class="fullroute-header">
        <div class="fullroute-header-text">FULL ROUTE INFORMATION</div>
    </div>
    <div class="fullroute-overview">
        <div class="fullroute-overview-bookingref">
            Booking reference number: xxxxxxxxxxxx
        </div>
        <div class="fullroute-overview-depart">
            DEPARTURE
        </div>
        <div class="fullroute-overview-return">

        </div>
    </div>
</body>
</html>

I expect the HTML to look like the HTML template, apart from the data.

I think I'm doing something wrong, but let me know

yhnx

**Comment by jeroenvipper** [comment]
It seems the HTML and the images were not stored right.

<img width="626" alt="2021-05-12" src="https://user-images.githubusercontent.com/84079511/118008963-e887ce00-b34d-11eb-829c-df904ca67ab0.png">
<img width="626" alt="2021-05-12 (1)" src="https://user-images.githubusercontent.com/84079511/118008966-e9206480-b34d-11eb-9358-879cdcdcf7ad.png">

**Comment by jeroenvipper** [comment]
<!DOCTYPE HTML>
<html lang='en' xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <title>Hello World</title>

    
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Fraunces:ital,wght@0,400;0,700;1,400;1,700&amp;display=swap"
          title="Fraunces" />

    <style>
        body {
            font-family: 'Fraunces', sans-serif;
            font-size: 14pt;
        }


        .fullroute-header {
            width: 700px;
            height: 87px;
            background: #692E87 0% 0% no-repeat padding-box;
            box-shadow: 0px 3px 6px #00000029;
            border-radius: 10px 10px 0px 0px;
            opacity: 1;
            overflow: hidden;
        }

        .fullroute-header-text {
            padding-top: 72px;
            height: 100%;
            width: 300px;
            text-align: right;
            letter-spacing: 0px;
            color: #FFFFFF;
            text-transform: uppercase;
            opacity: 1;
            float: right;
            overflow: hidden;
        }

        .fullroute-overview {
            top: 40px;
            left: 57px;
            width: 700px;
            height: 587px;
            background: #692E87 0% 0% no-repeat padding-box;
            box-shadow: 0px 3px 6px #00000029;
            border-radius: 0px 0px 10px 10px;
            opacity: 1;
            overflow: hidden;
        }

        .fullroute-overview-bookingref {
            top: 10px;
            height: 50px;
            width: 700px;
            color: #FFFFFF;
            text-transform: uppercase;
            opacity: 1;
            float: left;
            background-color: yellow;
            overflow: hidden;
        }

        .fullroute-overview-depart {
            top: 20px;
            height: 100%;
            width: 300px;
            color: #FFFFFF;
            text-transform: uppercase;
            opacity: 1;
            float: left;
            background-color: red;
            overflow: hidden;
        }

        .fullroute-overview-return {
            top: 20px;
            height: 100%;
            width: 300px;
            text-align: right;
            color: #FFFFFF;
            text-transform: uppercase;
            opacity: 1;
            float: right;
            background-color: green;
            overflow: hidden;
        }
    </style>
    
    <base href='https://raw.githubusercontent.com/richard-scryber/scryber.core/master/Scryber.Core.UnitTest/Content/' />
</head>
<body>
    <div class="fullroute-header">
        <div class="fullroute-header-text">FULL ROUTE INFORMATION</div>
    </div>
    <div class="fullroute-overview">
        <div class="fullroute-overview-bookingref">
            Booking reference number: xxxxxxxxxxxx
        </div>
        <div class="fullroute-overview-depart">
            DEPARTURE
        </div>
        <div class="fullroute-overview-return">

        </div>
    </div>
</body>
</html>

**Comment by jeroenvipper** [comment]
<body>
    <div class="fullroute-header">
        <div class="fullroute-header-text">FULL ROUTE INFORMATION</div>
    </div>
    <div class="fullroute-overview">
        <div class="fullroute-overview-bookingref">
            Booking reference number: xxxxxxxxxxxx
        </div>
        <div class="fullroute-overview-depart">
            DEPARTURE
        </div>
        <div class="fullroute-overview-return">

        </div>
    </div>
</body>

**Comment by jeroenvipper** [comment]
<img width="705" alt="2021-05-12 (2)" src="https://user-images.githubusercontent.com/84079511/118009610-7d8ac700-b34e-11eb-9009-8a4bc24230e3.png">

**Comment by richard-scryber** [comment]
Hey Jeroen, welcome to Scryber (and GitHub I believe).

Thanks for submitting this, really appreciate it - and getting the example images if perfect. I think the first thing is, we are actually working on getting the float left and right implemented and sorted at this very moment. There is an alpha version of our Nuget package out there but it is definitely alpha. Beta and final should be available in the coming week for our May release (along with gradients).

If you want to replicate a template that you are building for viewing on a browser and a document, then we do support the @media for print rules, and what you are trying to get to is achievable with the supported css and layout available in scryber - except individual border radii, text-transform, and shadows - We still have a bit to do for those.

There are some differences in positioning and alignment between scryber and the browser rendering, but these are mainly down to pages, headers and columns and the flow of content rather than forcing locations.

If you are happy to, then I can help with a template, but if you start with no explicit positioning and set heights, and then alignment on parents rather than children it should all flow together.

**Comment by jeroenvipper** [comment]
Hi Richard,

Really appreciate your prompt reply. I'm not new to github, just new with this account ;-)  

Key benefit of your code is that it does not rely on GDI+, which means we can render PDF documents on Azure app services. 

So thank you a lot for this! As we are a travel-tech company I want to use Scryber.core to generate a ticket for our travelers. I'm going to share you some designs and I'd love some guidlines on how to accomplish this. 

Kind regards and lot's of respect,
Jeroen de Visser

<img width="273" alt="ticket1" src="https://user-images.githubusercontent.com/84079511/118027390-2858b080-b362-11eb-9a16-c535efc4a5e2.PNG">
<img width="236" alt="ticket2" src="https://user-images.githubusercontent.com/84079511/118027403-2bec3780-b362-11eb-8b8b-941e82125285.PNG">

**Comment by richard-scryber** [comment]
These are a lovely set of designs to work to, and happy to help. We are going to struggle with drop shadows, but borders would hopefully be ok. :-)

**Comment by richard-scryber** [comment]
Hi Jeroen

I've put a bit together based on the designs. I hope it makes sense...

```<!DOCTYPE HTML>
<html lang='en' xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <title>Vipper Itinerary</title>
  	<style type='text/css' >
      
      body{
        padding: 20px;
        font-size: 12pt;
      }
      
      .block{
        border-radius: 5px;
        background-color: #EEE;
        border:solid 2px #999;
        page-break-inside:avoid;
        overflow:hidden;
        margin-top: 30pt;
        color:#692E87;
        
      }
      
      .block > .header {
        padding: 20px;
        border-bottom: solid 2px #999;
        font-weight: bold;
      }
      
      .block.title{
        background-image: url(https://www.scryber.studio/assets/ScyberLogo2_alpha_small.png) 20px 40px no-repeat;
        background-repeat: no-repeat;
        background-size: 50px;
        background-color: #692E87;
        color: white;
        text-align:right;
        margin-top: 0px;
      }
      
      .block .content{
        background-color:white;
        color: #222;
        padding: 20pt;
        text-align:left;
      }
      
      .block .split{
        column-count:2;
      }
      
      .block .left{
        break-after:always;
        border-right: solid 1px #999;
      }
      
      .block .right{
        
      }
      
      .detail{
        margin-top: 20px;
        padding: 10px;
        border-bottom: solid 1px #999;
        margin-bottom: 20px;
      }
  </style>
</head>
<body>
    <div class='block title'>
      <div class='header' >
        FULL ROUTE INFORMATION
      </div>
      <div class='content'>
        <strong>Booking Reference: {@:Model.BookingRef}</strong>
        <div class='detail split'>
      	<div class='left' >
          <span style='font-weight:bold;'>Outbound</span>
          <template data-bind='{@:Model.Outbound.Route}' >
            <div class='{@.Type}' >{@:.Provider}</div>
          </template>
        </div>
         <div class='right'>
           Right
         </div>
        </div>
        Footer
      </div>
      
   </div>
  
  <div class='block'>
      <div class='header' >
        PASSENGER INFORMATION
      </div>
      <div class='content split'>
        Hello World from scryber.
      </div>
   </div>
</body>
</html>

```

Based on the model

```

{
	"BookingRef" : "1234567",
	"Outbound" : {
		"Date": "12th May 2021",
		"Route": [
				{ "Provider" : "Lufthansa", "Type": "Lufthansa" },
				{ "Provider" : "Vipper", "Type": "VIP" }
			]
		}
}

```

To get an output similar to

<img width="815" alt="image" src="https://user-images.githubusercontent.com/65354830/118042619-34497000-b36c-11eb-84fe-05779ce3bda0.png">

I'll see what else I can do and save it to our sample playground. Hope it helps.

**Comment by ggrgovski** [comment]
Good luck Jeroen 😁

**Comment by jeroenvipper** [comment]
Thank you very much @richard-scryber! 

I struggled a bit with the font, especially the bold one, but I managed to get this working:

   <link href='http://fonts.googleapis.com/css?family=Roboto:400,100,300,100italic,300italic,400italic,500italic,500,700,700italic,900,900italic' rel='stylesheet' type='text/css' />
 
 font-family: 'Roboto'

I think I can proceed now!

**Comment by richard-scryber** [comment]
Glad to hear that Jeroen, I know the link that google provides for using their fonts is not XHTML compliant as it has a & and no closing tag.

If you want to, take the truetype file reference out of the css google fonts is feeding, and put it in your own local css file.

e.g.

```
@font-face {
            font-family: 'Long Cang';
            font-style: normal;
            font-weight: 400;
            src: url(https://fonts.gstatic.com/s/longcang/v5/LYjAdGP8kkgoTec8zkRgrQ.ttf) format('truetype');
        }
```

As this will save you a round trip each time to get the css file before checking that it already has downloaded the font file.
