### ISSUE TITLE
Can't figure how to format date and time

### ISSUE THREAD

**Issue by jeroenvipper** [richard-scryber/scryber.core#51]
I have searched the documentation and tried some ways to format a .Net DateTime member as 

```
<time date-format="dd MMM yyyy">{@:model.DepartureDate}</time
```
This does not work, since this element expects a different format then the string output of DateTime

In the xml doc version you could do @:model.DepartureDate.Time

Please let me know how to achieve this without putting it formatted in the model.

**Comment by richard-scryber** [comment]
Hey Jeroen - The content within the time element is treated as text, and an attempt will be made to parse it as a date time value, however we do support the datetime attribute for setting an explicit .Net date time value.

`Date: <time date-format="dd MMMM yyyy" datetime="{@:model.DateTimeValue}" />`

Sorry the documentation on this is a bit poor, I'll update with examples.

**Comment by jeroenvipper** [comment]
Thank you so much!
