### ISSUE TITLE
Support binding to decimal type in the Number component

### ISSUE THREAD

**Issue by tim-biasoft** [richard-scryber/scryber.core#53]
Using a decimal type in the model as a binding value for a Number component gives me this exception:
```
Cannot bind the values for 'numb:numb1' with id numb1
System.ArgumentException: Object of type 'System.Decimal' cannot be converted
to type 'System.Double'.
 at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo
culture, Boolean needsSpecialCast)
 at System.RuntimeType.CheckValue(Object value, Binder binder, CultureInfo
culture, BindingFlags invokeAttr)
 at System.Reflection.MethodBase.CheckArguments(Object[] parameters, Binder
binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
 at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj,
BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
 at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags
invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
 at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value,
BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
 at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value,
Object[] index)
 at Scryber.Binding.BindingItemExpression.BindComponent(Object sender,
PDFDataBindEventArgs args) in
/Users/richardhewitson/Projects/Scryber.Core/Scryber.Core/Scryber.Generation/Bi
nding/BindingItemExpression.cs:line 80
```
I'm using generated models from Entity Framework where the SQL data type is decimal so it would be inconvenient to have to change the type.

I made the following change in scryber.core\Scryber.Generation\Binding\BindingItemExpression.cs method BindComponent
```diff
                             value = value.ToString();
 
                         else if (this.IsParsable(out parse) && ((value is string) || (value is IConvertible)))
                         {
                             value = parse.Invoke(null, new object[] { value.ToString() });
+                        } else if ((value is decimal decValue) && _property.PropertyType == typeof(double))
+                        {
+                            args.Context.TraceLog.Add(TraceLevel.Verbose, "Item Binding","Value is decimal, property is double: converting to double.");
+                            value = decimal.ToDouble(decValue);
                         }
                         
                         this._property.SetValue(sender, value, null);
                     }
                     else if (args.Context.ShouldLogVerbose)
```

This solves the problem for me but I'm not convinced it's the most appropriate fix.

**Comment by richard-scryber** [comment]
I can take a look at this today / tomorrow Tim. Put it a bit lower on the priority list as it looked like you had good a working solution, and needed to get float left etc sorted. If I don't use this code directly I will check in the update and let you know. Will be in the next package release too.

**Comment by tim-biasoft** [comment]
Perfect, thanks RIchard.

**Comment by richard-scryber** [comment]
I have added the check of direct conversion through the IConvertible interface into BindingItemExpression, rather than just for decimals to doubles.

As we are in a try catch block, if it is convertible, but not supported then it should be handled OK. I am not expecting any degradation of performance either - could you compare? The trace log will help if you have long documents.

                        ...
                        else if(value is IConvertible)
                        {
                            value = (value as IConvertible).ToType(this.Property.PropertyType, null);
                        }

Any probs, just let us know. And thanks for picking it up.

**Comment by tim-biasoft** [comment]
That's definitely a better approach. Stopwatch gives less than 0.67 seconds to generate 26 documents (mostly single page), including saving them so I don't think performance is an issue :)

**Comment by richard-scryber** [comment]
Glad to see it working for you, and the performance is still up there.

40 documents per second is great 😄
