### ISSUE TITLE
Binding using indexed access to arrays causes an exception, works with List

### ISSUE THREAD

**Issue by tim-biasoft** [richard-scryber/scryber.core#54]
[binding_parameters](https://github.com/richard-scryber/scryber.core/blob/master/docs/binding_parameters.rst) mentions using arrays and the code in [BindingItemExpression](https://github.com/richard-scryber/scryber.core/blob/cc13b4a9c8230421ffda4ef7804456d15537531a/Scryber.Generation/Binding/BindingItemExpression.cs#L308) is looking for a property named "Item" to access which is present in IList:

```c#
            protected override object DoGetMyValue(object parent, PDFDataContext context)
            {
                System.Reflection.PropertyInfo pi = parent.GetType().GetProperty("Item", new Type[] { typeof(int) });
                if (null == pi)
                    throw new ArgumentOutOfRangeException("Item[int]");

                return pi.GetValue(parent, new object[] {IndexValue});
            }
```
System.Array does implement IList but [Remarks](https://docs.microsoft.com/en-us/dotnet/api/system.array.system-collections-ilist-item?view=net-5.0#remarks) says to use Item it has to be cast to IList as it's an "explicit interface member implementation". All a bit too tricksy for me! Personally I think just supporting List is fine.

**Comment by richard-scryber** [comment]
Good shout Tim. Hadn't spotted the dependency there. Let me check.

**Comment by richard-scryber** [comment]
I have added support for IList in the Item binding expression, should be available in code and the next package.
Should be faster too. The test is in the bodyWithBinding.html

                if (parent is IList)
                    return (parent as IList)[IndexValue];
                else
                {
                    System.Reflection.PropertyInfo pi = parent.GetType().GetProperty("Item", new Type[] { typeof(int) });
                    if (null == pi)
                        throw new ArgumentOutOfRangeException("Item[int]");

                   return pi.GetValue(parent, new object[] {IndexValue});
               }

Any problems just shout. :-)

**Comment by tim-biasoft** [comment]
All looks good, still working as it was - I'm using List not arrays now anyway.
