### ISSUE TITLE
Allowing to combine templates with liquid despite Expressive implementation

### ISSUE THREAD

**Issue by bashuss** [richard-scryber/scryber.core#59]
**Is your feature request related to a problem? Please describe.**

I read here about Expressive implementation: https://github.com/richard-scryber/scryber.core/issues/52#issuecomment-882730817
{{...}} handle bar syntax is described there. 
I am currently trying out to use scryber.core within orchard.core cms (https://github.com/OrchardCMS/OrchardCore) using the way templates are accessed and created there to build html as input for scryber. 
But orchard.core uses liquid templating language which makes use of handle bar notation.

**How could it work, not to create conflicts there?**

I guess (as I am not experienced in scryber), the usual way would be to first create the scryber-template with the methods of orchard.core. So all the handlebar notation used for scryber would need to be escaped in some way.

- One solution might be, that the document parser in scryber can recognize a registered escaped version?
- Another solution might be, to add an extension to the liquid implementation in orchard as a plugin, that renders scryber handle bar notation, but in this case, the rendered result can not recursively reevaluated by liquid interpreter...

**Describe the solution you'd like**
I would like to register different start and end tags with the parser, while "{{" and "}}" are the standard.

**Describe alternatives you've considered**
I might just run a string.Replace() or regex.Replace() on the cms generated template before I put it into scryber. I already have to do this for `<br>` and `<hr>` tags, as the wysiwyg html editor currently in the cms generates them non xml conform.

**Comment by richard-scryber** [comment]
Hi Bashuss, I know orchard - great stuff.

I can definitely look into using a separate notation as the {{....}} notation is just a shortcut for a {calc:...} notation.

If you were to use {{ }} for anything Orchard that was to be pre-processed and {calc:...} for anything to be processed by scryber, then it should work. It is just not as 'pretty' :-)

Let me know if you need to get some escapes in there.
