### ISSUE TITLE
allow css :before, :after and Content: = allow to include FontAwesome like styling with symbols

### ISSUE THREAD

**Issue by bashuss** [richard-scryber/scryber.core#60]
**Is your feature request related to a problem? Please describe.**
I would like to be able to use already existing styled html as part of the templates for scryber. These make use of FontAwesome Styling with `:before` and `:after` and `Content:'...'`

**Describe the solution you'd like**
I would like to use the classic way to include fontAwesome in Html to work also in PDF export with scryber: Import font and styles by css and use like `<i class="fas fa-info-circle"></i>` or `<a class="fas fa-external-link-alt" href=..."`

**Describe alternatives you've considered**
Adding a modified fontAwesome stylesheet for printing or pdf output - I have not researched yet, how this could work.

**Comment by richard-scryber** [comment]
I can definitely look into this. If it's simple I can sort, but I have a horrid suspicion my layout engine will baulk at the font requirements. Some of the SVG icon sets work.

**Comment by richard-scryber** [comment]
It has ben a while, but just checked in code that can support the ::before and ::after pseudo classes, along with content (excluding counters or linear gradients). We are getting there, and this will make it into the next release.
