### ISSUE TITLE
bootstrap css font

### ISSUE THREAD

**Issue by gmbeas** [richard-scryber/scryber.core#61]
hi, when i want to use bootstrap css it throws the following error to me
`<link rel='stylesheet' href='https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css' integrity='sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T' crossorigin='anonymous' />`

`he layout of component 'text1' failed. No fonts could be found that matched the selector '-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,"Noto Sans",sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol","Noto Color Emoji"' with styleBold, Italic`

I am passing html to pdf, is it necessary to preload the indicated fonts?

I appreciate that you can guide me

**Comment by Jogai** [comment]
Bootstrap default font has a few defaults to fall back to. Loading fonts can be done, see: https://scrybercore.readthedocs.io/en/latest/drawing_fonts.html#font-face-loading

**Comment by khanmubeen** [comment]
Hi, I have been in similar situation. Tried to set bootstrap, but result is not as expected. Does Scryber Html Engine support external link bootstrap css. Link above or documentation is unclear. Thank you for your efforts :)

**Comment by richard-scryber** [comment]
Hi Mubeen, 

scryber is not designed as a web page print engine, but we use xhtml as the template description (to reduce learning effort and give us a predictable framework for the layout). 

You may be able to take some elements from bootstrap, but that library is designed to provide a flexible responsive web page layout, that doesn't translate well to our fixed size document page layout. It will import the css, but not use many of the features (and some may break).

**Comment by averybusinesssolutions** [comment]
`@font-face{
            font-family: AveryBusiness;
            src: url('Archive.otf') format('opentype');
        }`

When I try to add a font face directly I also get the same error. 

Is there just no support for custom fonts? Or does it have to be in a specific format?

**Comment by richard-scryber** [comment]
Hi - if you set a 'font-style:normal' and 'font-weight: 400', on the @font-face, does it still fail? The font support should work, and the fallback, but I am definitely open to there being loading or selector issues.

Would love to know if it doesn't (or does) work.

**Comment by richard-scryber** [comment]
If you wanted to send a sample or font file I can test that would be amazing.

**Comment by averybusinesssolutions** [comment]
[archive.zip](https://github.com/richard-scryber/scryber.core/files/10528643/archive.zip)

`@font-face {
            font-family: AveryBusiness;
            font-style: normal;
            font-weight: 400;
            src: url('Archive.otf') format('opentype');
        }`

Fails with the message below 

`Scryber.PDFLayoutException : The layout of component 'text1' failed. No fonts could be found that matched the selector AveryBusiness with styleRegular
---- System.NullReferenceException : No fonts could be found that matched the selector AveryBusiness with styleRegular`

Attached is the font I am using.

**Comment by richard-scryber** [comment]
Thanks - I am taking a look, I am getting an error with the font loading as it's using a path local to the dlls, rather than the template file I have set up, but I'm sure I can figure something, and get a fix in.

**Comment by averybusinesssolutions** [comment]
I pulled down the new code but I'm not sure how to help you with the unit tests. I'm not well versed in pdf generation. It looks great though the one unit test you have for it ran successfully and has the correct font. 

Thank you for your work on this. If you need anything from me just let me know.

**Comment by richard-scryber** [comment]
Closing this as working, as I think we are good and no-one else has raised it back up
