### ISSUE TITLE
Support for .NET 6

### ISSUE THREAD

**Issue by ringwood-dsg** [richard-scryber/scryber.core#82]
**Is your feature request related to a problem? Please describe.**
I have a .NET 6 solution that's at a stage where it is impossible to move it to .NET 5 in order to make use of this amazing piece of kit. So...I forked the repository and manually changed the project(s) to reference .NET 6 instead of .NET 5. This is absolutely no problem, however, the OpenType.dll assembly/project is not in source so we're unable to move that assembly to .NET 6.

**Describe the solution you'd like**
Add support for .NET 6

**Describe alternatives you've considered**
As mentioned above, I don't have access to the source for the OpenType assembly and as such I've referenced the newly built .NET 6 assemblies along with the .NET 5 assembly for OpenType. This seems to work but will (most likely) cause issues at some point.

**Comment by richard-scryber** [comment]
Hi Juan, thanks for the really positive feedback. Nice to receive!

I am actually working on a .Net 6 implementation at the moment. Trying to make it run as a web assembly. All the new code is in the 'documentation' branch. Remote loading of .ttf and images should now work.

Alternatively OpenType is also open source, so you could reference the project itself in your fork (just separated out for convenience)
https://github.com/richard-scryber/Scryber.Core.OpenType

If there is anything that doesn't work for you, just let me know.

**Comment by bykka** [comment]
I tested a simple "hello world" application in AWS Lambda with .net6 runtime (typically it is pretty minimalistic environment) and it works

**Comment by richard-scryber** [comment]
.Net 6 is supported these days and should work in AWS, Azure and also Blazor Web Assembly for client side generation.
