### ISSUE TITLE
Support For Vertical Text

### ISSUE THREAD

**Issue by 0NotApplicable0** [richard-scryber/scryber.core#91]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to rotate HTML.

**Describe the solution you'd like**
In CSS their exists transforms, with these you can use as rotate() to rotate HTML a given degree.

**Describe alternatives you've considered**
Another approach would be to use SVGs. This approach is not restricted and is not generalized to all HTML components.

**Comment by richard-scryber** [comment]
Hey dude. I actually think I have most of this working under the hood already, and to add CSS parsing for the transform should be OK, just the ordering and centering. 

I can take a look at what I have now and see how it matches the expected output in html

**Comment by richard-scryber** [comment]
Happy new year - I have just released a new version for the Scryber.Core package - 6.0.0.14-beta that should support this with the CSS rotate() etc. on any block container. 

[Rotated text sample](https://www.paperworkday.net/preview.html?ui=Paging%2CZoom%2CCode%2CEdit&template=https%3A%2F%2Fraw.githubusercontent.com%2Frichard-scryber%2FPaperworkDayDocs%2Fmain%2Fdocs%2F_samples%2Ftransform%2Frotate.html)

It might take a bit of work to get the right position, but that is normal with the transform in my non-math-genius opinion.

Hope it works for you.

**Comment by 0NotApplicable0** [comment]
Great news, thanks for working on this!
