### ISSUE TITLE
NullReferenceException on parsing document

### ISSUE THREAD

**Issue by hahyes** [richard-scryber/scryber.core#98]
Hi there,

I can't make a conversion using ScryberCore and I have no idea why Exception is happening.
I'm trying to convert HTML code into PDF, yet it seems like library can't parse my code at all.

This code is happily used in TuesPechkin, so I'm sure it is proper HTML code. It is showing properly in browsers too.

My code is almost the same used in docs as tutorial:
```csharp
        static void Main(string[] args)
        {
            System.Console.WriteLine("Beginning PDF Creation");

            //Get the working and temp directory
            string workingDirectory = System.Environment.CurrentDirectory;
            string tempDirectory = System.IO.Path.GetTempPath();

            //The path to the input template - could be a stream, text reader, xml reader, resource etc
            var path = System.IO.Path.Combine(workingDirectory, "index.html");

            //The path to the output file - could be a stream
            var output = System.IO.Path.Combine(workingDirectory, "HelloWorld.pdf");

            //Load the template and output to the directory
            var doc = Document.ParseDocument(path);
            doc.SaveAsPDF(output, System.IO.FileMode.OpenOrCreate);

            //Notify completion
            System.Console.WriteLine("PDF File generated at " + output);
            System.Console.ReadKey();
        }
```

**To Reproduce**
1. Use https://pastebin.com/T3qr6Ueb this pastebin and pasted code above, save HTML code to file and put path to file in `Document.ParseDocument` method call.
2. `NullReferenceException` happen.

**Expected behavior**
PDF file I guess.

**Specification:**
- OS: Windows 11
- Visual Studio 2022
- .NET 5 (but tried on .NET 7 too)
- ScryberCore 5.0.7 [latest NuGet]s

**Comment by ahmedzakaria432** [comment]
same here i tried this and have same issue
`  using (var reader = new StringReader(viewAsString))
                {
                    using (var doc = Document.ParseDocument(reader, ParseSourceType.DynamicContent))
                    {
                        
                        using (var stream = new MemoryStream())
                        {
                            await doc.SaveAsPDFAsync(stream);
                            return stream.ToArray();
                        }
                    }
                }
`
and i got this exception 
Scryber.PDFParserException: The XmlParser could not parse the source file ''. Object reference not set to an instance of an object.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.

**Comment by ivan-furdek** [comment]
'The html tag has the xmlns attribute - this tells scryber to expect an XHTML formatted document, rather than any other document description. It is required, although you can use prefixes and any other supported namespaces (see drawing_paths)'

https://scrybercore.readthedocs.io/en/latest/2_document/2_template_structure.html

**Comment by hahyes** [comment]
@ivan-furdek Thank you very much! I tried xmlns earlier but it didn't work. But after using whole structure like in docs:

```
<?xml version="1.0" encoding="utf-8" ?>
<?scryber append-log='true' log-level='Messages' parser-log='true' ?>
<!DOCTYPE HTML>
<html xmlns='http://www.w3.org/1999/xhtml'>
```

It works now! I got other parsing errors but I can fix it myself. One more time, thank you! <3

**Comment by richard-scryber** [comment]
@hahyes - It was bugging me, so I added a unit test and used HtmlAgilityPack package to convert your html content to xhtml.

With a bit of conversion fixes I could get your content to parse with the following class


    public static class HtmlParser
    {
        const string htmlXmlns = "http://www.w3.org/1999/xhtml";

        private static  System.Text.RegularExpressions.Regex restoreHtmlEntities =
            new System.Text.RegularExpressions.Regex("&amp;([^ ]{1,8});");

        public static  Document Parse(string html, string path, ParseSourceType type, bool forceXHTMLNamespace = true)
        {
            //Use agility pack to load the html

            HtmlAgilityPack.HtmlDocument adoc = new HtmlAgilityPack.HtmlDocument();
            adoc.LoadHtml(html);


            //make sure we have the namespace on the html node

            var node = adoc.DocumentNode.SelectSingleNode("//html");
            if (null == node)
            {
                throw new Scryber.PDFParserException("Cannot parse the html content as the root 'html' node could not be found");
            }
            else if (node.Attributes.Contains("xmlns") == false)
                node.Attributes.Add("xmlns", htmlXmlns);
            else
            {
                var xmlns = node.Attributes["xmlns"];
                if (xmlns.Value != htmlXmlns)
                {
                    if (forceXHTMLNamespace)
                        xmlns.Value = htmlXmlns;
                    else
                        throw new Scryber.PDFParserException("Cannot parse the html content as the namespace does not match the xhtml namespace");
                }
            }

            //output the document as xhtml

            adoc.OptionOutputAsXml = true;
            adoc.OptionPreserveXmlNamespaces = true;
            adoc.OptionWriteEmptyNodes = true;
            adoc.OptionAutoCloseOnEnd = true;

            StringBuilder content = new StringBuilder();
            using (var sw = new StringWriter(content))
            {
                using (var xml = new System.Xml.XmlTextWriter(sw))
                    adoc.Save(xml);
            }

            var xhtml = content.ToString();


            //HtmlAgilityPack will convert html entities such as &nbsp;
            //to &amp;nbsp; so we need to convert back

            var restored = restoreHtmlEntities.Replace(xhtml, (input) => {
                //first is full string second should be the characters between the &amp; and trailing ;
                var val = "&" + input.Groups[1].Value + ";"; 
                return val;
            });

            //finally we can parse the xhtml

            using (var sr = new StringReader(restored))
            {
                var doc = Document.ParseDocument(sr, path, type);

                return doc;
            }

        }
    }



You should be able to call this with the following and be more generic.

                using (var doc = HtmlParser.Parse(text, path, ParseSourceType.LocalFile))
                {
                    using (var stream = DocStreams.GetOutputStream("HahyesTest2.pdf"))
                    {
                        doc.SaveAsPDF(stream);
                    }
                }

I will look at adding it to the library, as I think many would find useful, but hopefully it helps. The raw output without doing anything was not bad.

[HahyesTest2.pdf](https://github.com/richard-scryber/scryber.core/files/10941466/HahyesTest2.pdf)
